"""empty message

Revision ID: 3e43ea7f3260
Revises: 
Create Date: 2018-04-13 19:58:15.770927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e43ea7f3260'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cemetery_entry', sa.Column('phone_of_cemetery', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cemetery_entry', 'phone_of_cemetery')
    # ### end Alembic commands ###
