"""empty message

Revision ID: 3fb0e38fc8ba
Revises: b7850963f1c5
Create Date: 2018-04-14 14:32:03.669373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fb0e38fc8ba'
down_revision = 'b7850963f1c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person_entry', sa.Column('nickname', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person_entry', 'nickname')
    # ### end Alembic commands ###
