"""empty message

Revision ID: b7850963f1c5
Revises: 3e43ea7f3260
Create Date: 2018-04-13 21:54:40.314344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7850963f1c5'
down_revision = '3e43ea7f3260'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person_entry', sa.Column('children', sa.Text(), nullable=True))
    op.add_column('person_entry', sa.Column('parents', sa.Text(), nullable=True))
    op.add_column('person_entry', sa.Column('siblings', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person_entry', 'siblings')
    op.drop_column('person_entry', 'parents')
    op.drop_column('person_entry', 'children')
    # ### end Alembic commands ###
